name: LADS
favicon: null
layout_spectrum: 0.46137692080810666
typography_spectrum: 0.7334933150559664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4124348312616348
  lightness: 0.5176750435493886
  saturation: 0.6444873863365501
  rhythmicContrast: 0.04861141531728208
purpose: []
